name: gltest
# either manually started, or on a schedule
on: [ push, workflow_dispatch ]
jobs:
  gltest:
    env:
        OPENLANE_TAG:           2023.02.14
        OPENLANE_IMAGE_NAME:    efabless/openlane:4cd0986b3ae550cdf7a6d0fba4e0657012f635d8-amd64
        OPENLANE_ROOT:          /home/runner/openlane
        PDK_ROOT:               /home/runner/pdk
        PDK:                    sky130B

    # ubuntu
    runs-on: ubuntu-latest
    steps:
    # need the repo checked out
    - name: checkout repo
      uses: actions/checkout@v3
      with:
          submodules: recursive

    # build PDK
    - name: pdk
      run: |
        cd $HOME
        git clone https://github.com/efabless/caravel_user_project.git
        cd caravel_user_project
        make install pdk-with-volare

    # install oss fpga tools
    - name: install oss-cad-suite
      uses: YosysHQ/setup-oss-cad-suite@v2
      with:
          python-override: true
          github-token: ${{ secrets.GITHUB_TOKEN }}
    - run: | 
        yosys --version
        iverilog -V
        cocotb-config --libpython
        cocotb-config --python-bin

    - name: test
      run: |
        cd src
        make clean
        GATES=yes make
        # make will return success even if the test fails, so check for failure in the results.xml
        ! grep failure results.xml

